=== EnmanuelParache/apple-news-format-schema/src/apple-news-format-schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "id": "https://schema.lonelyplanet.com/apple-news-format-scheama.json",
  "title": "Apple News Format schema",
  "description": "Describes article.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "string",
      "pattern": "^[0-9]+\\.[0-9]+$"
    },
    "identifier": {
      "type": "string",
      "pattern": "^[a-zA-Z0-9_-]{1,64}$"
    },
    "title": {
      "type": "string"
    },
    "language": {
      "type": "string"
    },
    "layout": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "columns": {
          "$ref": "#/definitions/absIntMin1"
        },
        "width": {
          "$ref": "#/definitions/absIntMin1"
        },
        "gutter": {
          "type": "integer",
          "multipleOf": 2.0,
          "minimum": 0
        },
        "margin": {
          "$ref": "#/definitions/absInt"
        }
      },
      "required": [
        "columns",
        "width"
      ]
    },
    "components": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/component"
      }
    },
    "advertisingSettings": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "bannerType": {
          "type": "string",
          "enum": [
            "any",
            "standard",
            "double_height",
            "large"
          ]
        },
        "frequency": {
          "type": "integer",
          "multipleOf": 1.0,
          "minimum": 0,
          "maximum": 10
        },
        "layout": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "margin": {
              "oneOf": [
                {
                  "$ref": "#/definitions/absInt"
                },
                {
                  "$ref": "#/definitions/margin"
                }
              ]
            }
          },
          "required": [
            "margin"
          ]
        }
      }
    },
    "subtitle": {
      "type": "string"
    },
    "metadata": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "authors": {
          "$ref": "#/definitions/uniqueStringsArray"
        },
        "campaignData": {
          "type": "object"
        },
        "canonicalURL": {
          "$ref": "#/definitions/httpURL"
        },
        "coverArt": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/coverArt"
          }
        },
        "excerpt": {
          "type": "string"
        },
        "keywords": {
          "allOf": [
            {
              "$ref": "#/definitions/uniqueStringsArray"
            },
            {
              "maxItems": 50
            }
          ]
        },
        "thumbnailURL": {
          "$ref": "#/definitions/URL"
        },
        "transparentToolbar": {
          "type": "boolean"
        },
        "videoURL": {
          "$ref": "#/definitions/httpURL"
        }
      },
      "patternProperties": {
        "^date(Created|Modified|Published)$": {
          "$ref": "#/definitions/iso8601"
        },
        "^generator(Identifier|Name|Version)$": {
          "type": "string"
        }
      }
    },
    "documentStyle": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "backgroundColor": {
          "$ref": "#/definitions/hexColor"
        }
      },
      "required": [
        "backgroundColor"
      ]
    },
    "textStyles": {
      "type": "object",
      "patternProperties": {
        ".+": {
          "$ref": "#/definitions/textStyle"
        }
      }
    },
    "componentLayouts": {
      "type": "object",
      "patternProperties": {
        ".+": {
          "$ref": "#/definitions/componentLayout"
        }
      }
    },
    "componentStyles": {
      "type": "object",
      "patternProperties": {
        ".+": {
          "$ref": "#/definitions/componentStyle"
        }
      }
    },
    "componentTextStyles": {
      "type": "object",
      "patternProperties": {
        ".+": {
          "$ref": "#/definitions/componentTextStyle"
        }
      }
    }
  },
  "required": [
    "version",
    "identifier",
    "title",
    "language",
    "layout",
    "components"
  ],
  "definitions": {
    "fillMode": {
      "type": "string",
      "enum": [
        "fit",
        "cover"
      ]
    },
    "horizontalAlignment": {
      "type": "string",
      "enum": [
        "left",
        "center",
        "right"
      ]
    },
    "verticalAlignment": {
      "type": "string",
      "enum": [
        "top",
        "center",
        "bottom"
      ]
    },
    "httpURL": {
      "type": "string",
      "pattern": "^https?://.+"
    },
    "bundleURL": {
      "type": "string",
      "pattern": "^bundle://.+"
    },
    "URL": {
      "type": "string",
      "pattern": "^(bundle|https?)://.+"
    },
    "colorStop": {
      "typpe": "object",
      "additionalProperties": false,
      "properties": {
        "color": {
          "$ref": "#/definitions/hexColor"
        },
        "location": {
          "$ref": "#/definitions/percentage"
        }
      },
      "required": [
        "color"
      ]
    },
    "linearGradient": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "linear_gradient"
          ]
        },
        "colorStops": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/colorStop"
          }
        },
        "angle": {
          "$ref": "#/definitions/degree"
        }
      },
      "required": [
        "type",
        "colorStops"
      ]
    },
    "videoFill": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "video"
          ]
        },
        "URL": {
          "$ref": "#/definitions/httpURL"
        },
        "stillURL": {
          "$ref": "#/definitions/URL"
        },
        "fillMode": {
          "$ref": "#/definitions/fillMode"
        },
        "horizontalAlignment": {
          "$ref": "#/definitions/horizontalAlignment"
        },
        "verticalAlignment": {
          "$ref": "#/definitions/verticalAlignment"
        },
        "loop": {
          "type": "boolean"
        }
      },
      "required": [
        "type",
        "URL",
        "stillURL"
      ]
    },
    "imageFill": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "image"
          ]
        },
        "URL": {
          "$ref": "#/definitions/URL"
        },
        "attachment": {
          "type": "string",
          "enum": [
            "scroll",
            "fixed"
          ]
        },
        "fillMode": {
          "$ref": "#/definitions/fillMode"
        },
        "horizontalAlignment": {
          "$ref": "#/definitions/horizontalAlignment"
        },
        "verticalAlignment": {
          "$ref": "#/definitions/verticalAlignment"
        }
      },
      "required": [
        "type",
        "URL"
      ]
    },
    "uniqueStringsArray": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "componentTextStyle": {
      "allOf": [
        {
          "$ref": "#/definitions/textStyle"
        },
        {
          "properties": {
            "dropCapStyle": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "numberOfLines": {
                  "type": "integer",
                  "multipleOf": 1.0,
                  "minimum": 2,
                  "maximum": 10
                },
                "backgroundColor": {
                  "$ref": "#/definitions/hexColor"
                },
                "fontName": {
                  "type": "string"
                },
                "numberOfCharacters": {
                  "type": "integer",
                  "multipleOf": 1.0,
                  "minimum": 1,
                  "maximum": 4
                },
                "numberOfRaisedLines": {
                  "$ref": "#/definitions/absInt"
                },
                "padding": {
                  "$ref": "#/definitions/absInt"
                },
                "textColor": {
                  "$ref": "#/definitions/hexColor"
                }
              },
              "required": [
                "numberOfLines"
              ]
            },
            "firstLineIndent": {
              "$ref": "#/definitions/absInt"
            },
            "hangingPunctuation": {
              "type": "boolean"
            },
            "hyphenation": {
              "type": "boolean"
            },
            "lineHeight": {
              "$ref": "#/definitions/absInt"
            },
            "linkStyle": {
              "$ref": "#/definitions/textStyle"
            },
            "paragraphSpacingBefore": {
              "$ref": "#/definitions/absInt"
            },
            "paragraphSpacingAfter": {
              "$ref": "#/definitions/absInt"
            },
            "textAlignment": {
              "type": "string",
              "enum": [
                "left",
                "right",
                "center",
                "justified",
                "none"
              ]
            },
            "textShadow": {
              "$ref": "#/definitions/textShadow"
            }
          }
        }
      ]
    },
    "strokeStyle": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "color": {
          "$ref": "#/definitions/hexColor"
        },
        "width": {
          "oneOf": [
            {
              "$ref": "#/definitions/absInt"
            },
            {
              "$ref": "#/definitions/unitsOfMeasure"
            }
          ]
        },
        "style": {
          "type": "string",
          "enum": [
            "solid",
            "dashed",
            "dotted"
          ]
        }
      }
    },
    "border": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "all": {
          "$ref": "#/definitions/strokeStyle"
        },
        "top": {
          "type": "boolean"
        },
        "right": {
          "type": "boolean"
        },
        "bottom": {
          "type": "boolean"
        },
        "left": {
          "type": "boolean"
        }
      }
    },
    "componentStyle": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "backgroundColor": {
          "$ref": "#/definitions/hexColor"
        },
        "fill": {
          "anyOf": [
            {
              "$ref": "#/definitions/imageFill"
            },
            {
              "$ref": "#/definitions/videoFill"
            },
            {
              "$ref": "#/definitions/linearGradient"
            }
          ]
        },
        "opacity": {
          "$ref": "#/definitions/percentage"
        },
        "border": {
          "$ref": "#/definitions/border"
        }
      }
    },
    "componentLayout": {
      "type": "object"
    },
    "textShadow": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "color": {
          "$ref": "#/definitions/hexColor"
        },
        "radius": {
          "type": "number",
          "minimum": 0,
          "maximum": 100
        },
        "opacity": {
          "$ref": "#/definitions/percentage"
        },
        "offset": {
          "type": "object",
          "additionalProperties": false,
          "patternProperties": {
            "^[xy]$": {
              "$ref": "#/definitions/shadowOffsetNumber"
            }
          },
          "required": [
            "x",
            "y"
          ]
        }
      },
      "required": [
        "color",
        "radius"
      ]
    },
    "textStyle": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "backgroundColor": {
          "$ref": "#/definitions/hexColor"
        },
        "fontName": {
          "type": "string"
        },
        "fontSize": {
          "$ref": "#/definitions/absIntMin1"
        },
        "orderedListItems": {
          "$ref": "#/definitions/listItemStyle"
        },
        "unorderedListItems": {
          "$ref": "#/definitions/listItemStyle"
        },
        "strikethrough": {
          "oneOf": [
            {
              "type": "boolean"
            },
            {
              "$ref": "#/definitions/textDecoration"
            }
          ]
        },
        "stroke": {
          "$ref": "#/definitions/textDecoration",
          "required": [
            "color"
          ]
        },
        "textColor": {
          "$ref": "#/definitions/hexColor"
        },
        "textShadow": {
          "$ref": "#/definitions/textShadow"
        },
        "tracking": {
          "$ref": "#/definitions/percentage"
        },
        "underline": {
          "oneOf": [
            {
              "type": "boolean"
            },
            {
              "$ref": "#/definitions/textDecoration"
            }
          ]
        },
        "verticalAlignment": {
          "type": "string",
          "enum": [
            "superscript",
            "subscript",
            "baseline"
          ]
        }
      }
    },
    "degree": {
      "type": "number",
      "minimum": -360,
      "maximum": 360
    },
    "percentage": {
      "type": "number",
      "minimum": 0,
      "maximum": 1
    },
    "shadowOffsetNumber": {
      "type": "number",
      "minimum": -50,
      "maximum": 50
    },
    "textDecoration": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "color": {
          "$ref": "#/definitions/hexColor"
        },
        "width": {
          "$ref": "#/definitions/absIntMin1"
        }
      }
    },
    "listItemStyle": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "bullet",
            "decimal",
            "lower_alphabetical",
            "upper_alphabetical",
            "lower_roman",
            "upper_roman",
            "character",
            "none"
          ]
        },
        "character": {
          "type": "string",
          "maxLength": 1
        }
      },
      "required": [
        "type"
      ]
    },
    "hexColor": {
      "type": "string",
      "pattern": "^#([a-fA-F0-9]{3}|[a-fA-F0-9]{6}|[a-fA-F0-9]{8})"
    },
    "iso8601": {
      "type": "string",
      "pattern": "^(19|[2-9][0-9])[0-9]{2}-(0[1-9]|1[0-2])-(0[1-9]|([12][0-9]|3[01]))T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]\\+([01][0-9]|2[0-3]):[0-5][0-9]$"
    },
    "absInt": {
      "type": "integer",
      "multipleOf": 1.0,
      "minimum": 0
    },
    "absIntMin1": {
      "type": "integer",
      "multipleOf": 1.0,
      "minimum": 1
    },
    "unitsOfMeasure": {
      "type": "string",
      "pattern": "^[0-9]+(vh|vw|vmin|vmax|gut|cw|pt)$"
    },
    "role": {
      "type": "string",
      "enum": [
        "heading"
      ]
    },
    "component": {
      "type": "object",
      "properties": {},
      "required": [
        "role"
      ]
    },
    "margin": {
      "oneOf": [
        {
          "$ref": "#/definitions/absInt"
        },
        {
          "$ref": "#/definitions/unitsOfMeasure"
        }
      ]
    },
    "coverArt": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "image"
          ]
        },
        "URL": {
          "$ref": "#/definitions/URL"
        },
        "accessibilityCaption": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "URL"
      ]
    }
  }
}

=== EnmanuelParache/apple-news-format-schema/test/fixtures/valid/metadata.json
{
  "version": "1.7",
  "identifier": "metadata",
  "title": "metadata",
  "language": "en",
  "layout": {
    "columns": 7,
    "width": 1024,
    "margin": 125,
    "gutter": 40
  },
  "metadata": {
    "transparentToolbar": false,
    "excerpt": "Hello, World!",
    "thumbnailURL": "bundle://thumbnail.jpg",
    "coverArt": [
      {
        "type": "image",
        "URL": "bundle://coverart.jpg"
      }
    ],
    "links": [
      {
        "URL": "https://example.com/related",
        "relationship": "related"
      },
      {
        "URL": "https://example.com/promoted",
        "relationship": "promoted"
      }
    ]
  },
  "components": [
    {
      "role": "body",
      "format": "html",
      "text": "<p>Hello, World!</p>"
    }
  ],
  "componentTextStyles": {
    "default": {}
  }
}

=== EnmanuelParache/apple-news-format-schema/test/fixtures/valid/units-of-measure.json
{
  "version": "1.1",
  "identifier": "units-of-measure",
  "language": "en",
  "title": "Units of measure",
  "layout": {
    "columns": 24,
    "width": 1536,
    "margin": 64,
    "gutter": 64
  },
  "components": [
    {
      "role": "container",
      "style": {
        "border": {
          "all": {
            "width": "1",
            "style": "solid",
            "color": "#F00"
          }
        }
      },
      "components": [
        {
          "role": "heading",
          "layout": {
            "minimumHeight": "10vw"
          },
          "text": "Heading - 10vw"
        },
        {
          "role": "heading",
          "layout": {
            "minimumHeight": "10vh"
          },
          "text": "Heading - 10vh"
        },
        {
          "role": "heading",
          "layout": {
            "minimumHeight": "10vmin"
          },
          "text": "Heading - 10vmin"
        },
        {
          "role": "heading",
          "layout": {
            "minimumHeight": "10vmax"
          },
          "text": "Heading - 10vmax"
        },
        {
          "role": "heading",
          "layout": {
            "minimumHeight": "10pt"
          },
          "text": "Heading - 10pt"
        },
        {
          "role": "heading",
          "layout": {
            "minimumHeight": "10"
          },
          "text": "Heading - 10pt (without units)"
        },
        {
          "role": "heading",
          "layout": {
            "minimumHeight": 10
          },
          "text": "Heading - 10pt (int)"
        },
        {
          "role": "heading",
          "layout": {
            "minimumHeight": "10cw"
          },
          "text": "Heading - 10cw"
        },
        {
          "role": "heading",
          "layout": {
            "minimumHeight": "10gut"
          },
          "text": "Heading - 10gut"
        }
      ]
    }
  ]
}

=== EnmanuelParache/apple-news-format-schema/test/fixtures/valid/banner-advertisement.json
{
  "version": "1.7",
  "identifier": "Banner-Advertisement",
  "title": "Banner Advertisement",
  "language": "en",
  "layout": {
    "columns": 7,
    "width": 1024,
    "margin": 125,
    "gutter": 40
  },
  "components": [
    {
      "role": "banner_advertisement",
      "bannerType": "standard"
    },
    {
      "role": "container",
      "components": [
        {
          "role": "banner_advertisement"
        }
      ]
    }
  ],
  "componentTextStyles": {
    "default": {}
  }
}
